# Generated by Django 4.1.7 on 2023-04-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knihovna', '0005_kniha_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
